### ISSUE TITLE
taxonomy command does shuffles order of incoming taxa

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept-cli#26] opened 2019-08-14 13:58 UTC
To be compliant with the other commands in the Unipept CLI, the `taxonomy` command should preserve the order and frequency of the incoming taxa. It should also return an entry for those taxa that could not be retrieved from the Unipept database, to make the number of input lines equal the number of output lines.

_[Original issue](https://github.ugent.be/unipept/unipept-cli/issues/26) by @pdawyndt on Fri May 08 2015 at 13:31._
_Closed by @bmesuere on Tue May 19 2015 at 21:04._

**Comment by bmesuere** [comment] 2019-08-14 14:01
This is a duplicate of unipept/unipept#490


_[Original comment](https://github.ugent.be/unipept/unipept-cli/issues/26#issuecomment-17305) by @bmesuere on Fri May 08 2015 at 13:40._

**Comment by bmesuere** [comment] 2019-08-14 14:01
This was fixed in the API.


_[Original comment](https://github.ugent.be/unipept/unipept-cli/issues/26#issuecomment-18085) by @bmesuere on Tue May 19 2015 at 21:04._

**Closed** 2019-08-14 14:10 UTC
Labels: enhancement, migrated
